# Generated by Django 3.1.6 on 2021-02-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='imate',
            new_name='image',
        ),
    ]
