# Generated by Django 3.1.6 on 2021-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20210202_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], max_length=5),
        ),
    ]
