# Generated by Django 3.1.6 on 2021-02-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='property/category/'),
            preserve_default=False,
        ),
    ]
