# Generated by Django 3.1.6 on 2021-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
